// Utility script to seed initial products
// This file can be used to populate the store with sample products

export const seedProducts = [
  // TORTEN
  {
    id: 'product_chocolate_deluxe',
    name: 'Schokoladentorte Deluxe',
    description: 'Saftige Schokoladentorte mit belgischer Schokolade, verfeinert mit Schokoladenganache und edler Dekoration. Ein Traum für alle Schoko-Liebhaber!',
    price: 45.00,
    category: 'cakes',
    image_url: 'https://images.unsplash.com/photo-1737700088028-fae0666feb83?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBjYWtlJTIwZWxlZ2FudHxlbnwxfHx8fDE3NjQ3ODk4NTd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: true,
    is_available: true,
  },
  {
    id: 'product_strawberry_dream',
    name: 'Erdbeertorte Dream',
    description: 'Frische Erdbeeren auf luftigem Biskuitboden mit zarter Vanillecreme. Perfekt für den Sommer und besondere Anlässe!',
    price: 42.00,
    category: 'cakes',
    image_url: 'https://images.unsplash.com/photo-1573730886197-8636f98b2de0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJhd2JlcnJ5JTIwY2FrZSUyMGZyZXNofGVufDF8fHx8MTc2NDc5MzQ3Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: true,
    is_available: true,
  },
  {
    id: 'product_red_velvet',
    name: 'Red Velvet Torte',
    description: 'Klassische Red Velvet Torte mit samtweichem Teig und Frischkäse-Frosting. Ein echter Hingucker auf jeder Feier!',
    price: 48.00,
    category: 'cakes',
    image_url: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWQlMjB2ZWx2ZXQlMjBjYWtlfGVufDF8fHx8MTc2NDc0MDMxNHww&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: true,
    is_available: true,
  },
  {
    id: 'product_lemon_delight',
    name: 'Zitronen Delight',
    description: 'Erfrischende Zitronentorte mit hausgemachtem Lemon Curd und feiner Baiserhaube. Leicht und sommerlich!',
    price: 38.00,
    category: 'cakes',
    image_url: 'https://images.unsplash.com/photo-1605466237772-cdc947448e3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsZW1vbiUyMGNha2UlMjB5ZWxsb3d8ZW58MXx8fHwxNzY0NzkzNDczfDA&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: false,
    is_available: true,
  },
  {
    id: 'product_carrot_cake',
    name: 'Karottenkuchen Premium',
    description: 'Saftiger Karottenkuchen mit Walnüssen, Zimt und cremigem Frischkäse-Frosting. Traditionell und köstlich!',
    price: 40.00,
    category: 'cakes',
    image_url: 'https://images.unsplash.com/photo-1607269832078-1a3bd22a306d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXJyb3QlMjBjYWtlJTIwbnV0c3xlbnwxfHx8fDE3NjQ3OTM0NzN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: false,
    is_available: true,
  },

  // COOKIES
  {
    id: 'product_chocolate_chip',
    name: 'Chocolate Chip Cookies',
    description: 'Klassische Cookies mit belgischen Schokoladenstückchen. Knusprig außen, weich innen. 12 Stück pro Packung.',
    price: 12.00,
    category: 'cookies',
    image_url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBjaGlwJTIwY29va2llc3xlbnwxfHx8fDE3NjQ3Njc3NTd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: true,
    is_available: true,
  },
  {
    id: 'product_macarons',
    name: 'Französische Macarons Mix',
    description: 'Bunte Macarons in 6 verschiedenen Geschmacksrichtungen: Vanille, Schokolade, Erdbeere, Pistazie, Zitrone und Himbeere. 12 Stück.',
    price: 18.00,
    category: 'cookies',
    image_url: 'https://images.unsplash.com/photo-1681589211939-cbb7402afbc1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xvcmZ1bCUyMG1hY2Fyb25zfGVufDF8fHx8MTc2NDc5MzQ3NHww&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: true,
    is_available: true,
  },
  {
    id: 'product_oatmeal_raisin',
    name: 'Hafer-Rosinen Cookies',
    description: 'Gesunde und leckere Hafer-Cookies mit saftigen Rosinen und einer Prise Zimt. 10 Stück pro Packung.',
    price: 10.00,
    category: 'cookies',
    image_url: 'https://images.unsplash.com/photo-1598968333180-9b4f6bc2bf52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvYXRtZWFsJTIwcmFpc2luJTIwY29va2llc3xlbnwxfHx8fDE3NjQ3OTM0NzR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: false,
    is_available: true,
  },
  {
    id: 'product_butter_cookies',
    name: 'Butterplätzchen Klassik',
    description: 'Traditionelle deutsche Butterplätzchen, zart und buttrig. Perfekt zum Kaffee! 15 Stück pro Packung.',
    price: 9.50,
    category: 'cookies',
    image_url: 'https://images.unsplash.com/photo-1717838208427-57ce44a503e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXR0ZXIlMjBjb29raWVzJTIwdmFuaWxsYXxlbnwxfHx8fDE3NjQ3OTM0NzR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: false,
    is_available: true,
  },
  {
    id: 'product_double_chocolate',
    name: 'Double Chocolate Cookies',
    description: 'Für echte Schoko-Fans! Dunkle Schokoladen-Cookies mit weißen und dunklen Schokostückchen. 10 Stück.',
    price: 13.50,
    category: 'cookies',
    image_url: 'https://images.unsplash.com/photo-1629750413458-90c737a1c57b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb3VibGUlMjBjaG9jb2xhdGUlMjBjb29raWVzfGVufDF8fHx8MTc2NDc5MzQ3NXww&ixlib=rb-4.1.0&q=80&w=1080',
    is_popular: true,
    is_available: true,
  },
];
